name: Run ELO Update Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Run script
        run: python script.py

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/OnlinEGD/cs-ranking.git

      - name: Commit updated files
        run: |
          git add ranking.csv processed_matches.csv
          git commit -m "Automated update [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
